postgres:
  build: .
  dockerfile: Dockerfile.postgres
  ports:
    - "5432"
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=pa55word

api:
  build: .
  dockerfile: Dockerfile
  links:
    - postgres
  ports:
    - "8080:8080"
