web:
  build: .
  dockerfile: Dockerfile
  links:
    - postgres
  ports:
    - "8080:8080"
postgres:
  image: postgres:latest
  ports:
    - "15432:5432"
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=
    - POSTGRES_DB=postgres
