test:
  restart: always
  build: .
  dockerfile: Dockerfile.test
  links:
    - postgres

postgres:
  restart: always
  build: .
  dockerfile: Dockerfile.postgres
  ports:
    - "5432"
  environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=pa55word
