
[[dependencies]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[dependencies]]
  branch = "master"
  name = "github.com/lib/pq"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/crypto"
